language: go
go:
  - 1.7
  - 1.6
  - 1.5

install:
  - go get -u github.com/Masterminds/glide
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - make bins

script:
 - make cover_ci

notifications:
  email:
    recipients:
      - cherami@uber.com
    on_success: always 
    on_failure: always
